services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ${HOST_WORKSPACE_PATH}/frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
      - "9229:9229"
      - "9230:9230"
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
      - BACKEND_URL=http://backend:8000
    networks:
      - default
      - devcontainer

  backend:
    build:
      context: ./backend
    volumes:
      - ${HOST_WORKSPACE_PATH}/backend/app:/app/app
    ports:
      - "8000:8000"
      - "5678:5678"
    networks:
      - default
      - devcontainer

networks:
  devcontainer:
    external: true
    name: m_poc_default
